[project]
name = "try2scrape"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.10"
dependencies = [
    "bs4>=0.0.2",
    "fake-useragent>=2.2.0",
    "loguru>=0.7.3",
    "pandas>=2.3.1",
    "requests>=2.32.4",
    "ruff>=0.12.2",
]
